#!/usr/bin/env bash
# Indefinitely writes "l am alive" to the file /tmp/my_process.
#   Pauses two seconds in between each message.


while true
do
 echo "l am alive!" >> /tmp/my_process
 sleep 2
done
